import type { CarListing } from "@/types/car"

export const mockCarListings: CarListing[] = [
  {
    id: "1",
    make: "BMW",
    model: "X6",
    variant: "xDrive40i",
    year: 2021,
    price: 136999,
    monthlyPayment: 1998,
    location: "Dubai",
    mileage: 179000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2,979",
    gccSpecs: true,
    image: "/images/cars/car-img-3.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: true,
    urgent: true,
    photoCount: 10,
    description:
      "BMW X6 Xdrive40i 2021 AWD | AGMC Warranty &amp; Full Service History | GCC Specs BMW X6 Xdrive40i 2021 AWD - Blue Car BMW X6 Xdri...",
  },
  {
    id: "2",
    make: "Mercedes-Benz",
    model: "C-Class",
    variant: "C 200",
    year: 2024,
    price: 208999,
    monthlyPayment: 3048,
    location: "Dubai",
    mileage: 10031,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "1,800",
    gccSpecs: true,
    image: "/images/cars/car-img-4.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 10,
    description:
      "Mercedes Benz C-200 Premium 2024 | Brand New Condition | Under Warranty &amp; Service Contract Mercedes Benz C-200 2024 Car Detail:- Make:...",
  },
  {
    id: "3",
    make: "Audi",
    model: "Q7",
    variant: "45 TFSI",
    year: 2022,
    price: 189999,
    monthlyPayment: 2799,
    location: "Sharjah",
    mileage: 28000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-5.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: false,
    urgent: true,
    photoCount: 15,
    description:
      "Audi Q7 45 TFSI 2022 | Premium Package | Full Service History | GCC Specs | Excellent Condition",
  },
  {
    id: "4",
    make: "Toyota",
    model: "Camry",
    variant: "SE",
    year: 2019,
    price: 65999,
    monthlyPayment: 999,
    location: "Dubai",
    mileage: 67000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2,500",
    gccSpecs: true,
    image: "/images/cars/car-img-6.webp",
    featured: false,
    dealType: "Fair Deal",
    canBeExported: true,
    urgent: false,
    photoCount: 8,
    description:
      "Toyota Camry SE 2019 | Well Maintained | Full Service History | GCC Specs | Clean Title",
  },
  {
    id: "5",
    make: "Lexus",
    model: "ES",
    variant: "350",
    year: 2021,
    price: 119999,
    monthlyPayment: 1799,
    location: "Abu Dhabi",
    mileage: 38000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,500",
    gccSpecs: true,
    image: "/images/cars/car-img-3.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 12,
    description:
      "Lexus ES 350 2021 | Premium Package | Under Warranty | GCC Specs | Excellent Condition",
  },
  {
    id: "6",
    make: "Audi",
    model: "RS Q8",
    variant: "",
    year: 2022,
    price: 439250,
    monthlyPayment: 6407,
    location: "Dubai",
    mileage: 21354,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4,000",
    gccSpecs: true,
    image: "/images/cars/car-img-4.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 18,
    description:
      "Approved Automotive: The UAE's Multi Award-Winning Benchmark for Premium Luxury Automotive. Over 150 Years of Automotive Experience Over 600 ⭐ ⭐ ...",
  },
  {
    id: "7",
    make: "Audi",
    model: "SQ5",
    variant: "",
    year: 2023,
    price: 236250,
    monthlyPayment: 3446,
    location: "Dubai",
    mileage: 42540,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-5.webp",
    featured: true,
    dealType: undefined,
    canBeExported: false,
    urgent: false,
    photoCount: 17,
    description:
      "Approved Automotive: The UAE's Multi Award-Winning Benchmark for Premium Luxury Automotive. Over 150 Years of Automotive Experience Over 600 ⭐ ⭐ ...",
  },
  {
    id: "8",
    make: "Audi",
    model: "RS Q8",
    variant: "",
    year: 2021,
    price: 369350,
    monthlyPayment: 5387,
    location: "Dubai",
    mileage: 40253,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4,000",
    gccSpecs: true,
    image: "/images/cars/car-img-6.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 18,
    description:
      "Approved Automotive: The UAE's Multi Award-Winning Benchmark for Premium Luxury Automotive. Over 150 Years of Automotive Experience Over 600 ⭐ ⭐ ...",
  },
  {
    id: "9",
    make: "Audi",
    model: "RS Q8",
    variant: "",
    year: 2020,
    price: 349150,
    monthlyPayment: 5093,
    location: "Dubai",
    mileage: 62474,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4,000",
    gccSpecs: true,
    image: "/images/cars/car-img-3.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 18,
    description:
      "Approved Automotive: The UAE's Multi Award-Winning Benchmark for Premium Luxury Automotive. Over 150 Years of Automotive Experience Over 600 ⭐ ⭐ ...",
  },
  {
    id: "10",
    make: "Audi",
    model: "RS Q8",
    variant: "",
    year: 2023,
    price: 560000,
    monthlyPayment: 8168,
    location: "Dubai",
    mileage: 16236,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4,000",
    gccSpecs: true,
    image: "/images/cars/car-img-4.webp",
    featured: false,
    dealType: undefined,
    canBeExported: false,
    urgent: false,
    photoCount: 17,
    description:
      "Vehicle Description Approved Automotive: The UAE's Multi Award-Winning Benchmark for Premium Luxury Automotive.Over 150 Years of Automoti...",
    updatedDate: "Jul 04, 2025",
    promotionalText:
      "Don't miss the current offer for the New 2025 Audi RS Q8 in Dubai!",
  },
  {
    id: "11",
    make: "BMW",
    model: "X5",
    variant: "xDrive40i",
    year: 2022,
    price: 285000,
    monthlyPayment: 4200,
    location: "Dubai",
    mileage: 25000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-5.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 14,
    description:
      "BMW X5 xDrive40i 2022 | Premium Package | Full Service History | GCC Specs | Excellent Condition",
  },
  {
    id: "12",
    make: "Mercedes-Benz",
    model: "GLE",
    variant: "450",
    year: 2023,
    price: 395000,
    monthlyPayment: 5800,
    location: "Abu Dhabi",
    mileage: 18000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-6.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 16,
    description:
      "Mercedes-Benz GLE 450 2023 | AMG Line | Under Warranty | GCC Specs | Premium Condition",
  },
  {
    id: "13",
    make: "Porsche",
    model: "Cayenne",
    variant: "S",
    year: 2022,
    price: 485000,
    monthlyPayment: 7100,
    location: "Dubai",
    mileage: 22000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2,900",
    gccSpecs: true,
    image: "/images/cars/car-img-3.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 19,
    description:
      "Porsche Cayenne S 2022 | Sport Package | Full Service History | GCC Specs | Pristine Condition",
  },
  {
    id: "14",
    make: "Range Rover",
    model: "Sport",
    variant: "HSE",
    year: 2021,
    price: 325000,
    monthlyPayment: 4750,
    location: "Sharjah",
    mileage: 35000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-3.webp",
    featured: false,
    dealType: "Fair Deal",
    canBeExported: true,
    urgent: false,
    photoCount: 13,
    description:
      "Range Rover Sport HSE 2021 | Dynamic Package | Service History | GCC Specs | Great Condition",
  },
  {
    id: "15",
    make: "Audi",
    model: "Q8",
    variant: "55 TFSI",
    year: 2023,
    price: 425000,
    monthlyPayment: 6200,
    location: "Dubai",
    mileage: 12000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-3.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 18,
    description:
      "Audi Q8 55 TFSI 2023 | S-Line Package | Under Warranty | GCC Specs | Excellent Condition",
  },
  {
    id: "16",
    make: "BMW",
    model: "M4",
    variant: "Competition",
    year: 2022,
    price: 375000,
    monthlyPayment: 5500,
    location: "Dubai",
    mileage: 15000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3,000",
    gccSpecs: true,
    image: "/images/cars/car-img-4.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: true,
    photoCount: 20,
    description:
      "BMW M4 Competition 2022 | Carbon Package | Track Ready | GCC Specs | Performance Beast",
  },
  {
    id: "17",
    make: "Mercedes-Benz",
    model: "AMG GT",
    variant: "63 S",
    year: 2021,
    price: 650000,
    monthlyPayment: 9500,
    location: "Abu Dhabi",
    mileage: 8000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4,000",
    gccSpecs: true,
    image: "/images/cars/car-img-5.webp",
    featured: true,
    dealType: "Great Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 22,
    description:
      "Mercedes-AMG GT 63 S 2021 | Performance Package | Low Mileage | GCC Specs | Supercar Performance",
  },
  {
    id: "18",
    make: "Lamborghini",
    model: "Urus",
    variant: "S",
    year: 2023,
    price: 850000,
    monthlyPayment: 12400,
    location: "Dubai",
    mileage: 5000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4,000",
    gccSpecs: true,
    image: "/images/cars/car-img-6.webp",
    featured: true,
    dealType: "Fair Deal",
    canBeExported: false,
    urgent: false,
    photoCount: 25,
    description:
      "Lamborghini Urus S 2023 | Carbon Package | Nearly New | GCC Specs | Ultimate Luxury SUV",
  },
];

export const trustedCars = [
  {
    id: "tc1",
    make: "Mercedes-Benz",
    model: "S-Class",
    year: 2023,
    price: 450000,
    location: "Dubai",
    fuelType: "Petrol",
    mileage: 5000,
    image: "/images/cars/car-img-4.webp",
  },
  {
    id: "tc2",
    make: "Range Rover",
    model: "Vogue",
    year: 2022,
    price: 380000,
    location: "Abu Dhabi",
    fuelType: "Petrol",
    mileage: 12000,
    image: "/images/cars/car-img-3.webp",
  },
  {
    id: "tc3",
    make: "BMW",
    model: "7 Series",
    year: 2024,
    price: 420000,
    location: "Sharjah",
    fuelType: "Petrol",
    mileage: 2000,
    image: "/images/cars/car-img-5.webp",
  },
]
