export const trustedCarsData = [
  {
    id: "tc1",
    make: "Mitsubishi",
    model: "Attrage",
    year: 2022,
    price: 29900,
    location: "Dubai",
    fuelType: "Petrol",
    mileage: 76290,
    photoCount: 2,
    image: "/images/cars/car-img-3.webp",
    approved: false,
  },
  {
    id: "tc2",
    make: "Mercedes-Benz",
    model: "GLE-Clas...",
    year: 2022,
    price: 399000,
    location: "Dubai",
    fuelType: "Petrol",
    mileage: 14457,
    photoCount: 18,
    image: "/images/cars/car-img-4.webp",
    approved: true,
  },
  {
    id: "tc3",
    make: "Land Rover",
    model: "Defender 11...",
    year: 2023,
    price: 475000,
    location: "Dubai",
    fuelType: "Petrol",
    mileage: 9992,
    photoCount: 17,
    image: "/images/cars/car-img-5.webp",
    approved: true,
  },
  {
    id: "tc4",
    make: "BMW",
    model: "X7",
    year: 2024,
    price: 520000,
    location: "Abu Dhabi",
    fuelType: "Petrol",
    mileage: 5200,
    photoCount: 15,
    image: "/images/cars/car-img-6.webp",
    approved: true,
  },
  {
    id: "tc5",
    make: "Audi",
    model: "Q8",
    year: 2023,
    price: 385000,
    location: "Sharjah",
    fuelType: "Petrol",
    mileage: 12800,
    photoCount: 11,
    image: "/images/cars/car-img-3.webp",
    approved: false,
  },
];
